baseURL = "https://cnyouwei.github.io/IEDA2540/"
languageCode = "en-us"
title = "IEDA 2540 Statistics for Engineers"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "IEDA 2540 Statistics for Engineers"
    subtitle = "Course Website"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Statistics for Engineers"
      logoHomeLink = "https://cnyouwei.github.io/IEDA2540/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    #[languages.en.menu]
    #  [[languages.en.menu.main]]
    #    identifier = "about"
    #    name = "About"
    #    url = "/about"
